name: Create Release Archive
on:
  push:

  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HHmmss
          utcOffset: "+01:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_branch.outputs.branch }}-${{ steps.current-time.outputs.formattedTime }}
          release_name: ${{ github.event.repository.name }} - Release ${{ steps.current-time.outputs.formattedTime }} - Branch ${{ steps.extract_branch.outputs.branch }}
          draft: false
          prerelease: false
  ZipRelease:
    runs-on: ubuntu-latest
    needs: [CreateRelease]
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: "beaconstat-release.zip"
          exclusions: "*.git* *.csv *.xls *.xlsx bs_config.php keys.php .* README.md"
      - name: Upload Release Asset
        id: upload-website-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./beaconstat-release.zip
          asset_name: beaconstat-${{ steps.extract_branch.outputs.branch }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset
        id: upload-changelog
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./CHANGELOG.md
          asset_name: CHANGELOG.md
          asset_content_type: application/zip
  ReleasesCleanup:
    needs: [CreateRelease, ZipRelease]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup of old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #repo: <owner>/<repoName> # defaults to current repo
          keep_latest: 3
          delete_tags: false
          delete_tag_pattern: develop # defaults to ""
